image:
  pullPolicy: Always

workers:
  etl-alpha:
    repository: "etl-monorepo-app"
    tag: "05ab57a"
    dbType: "mysql"   
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-alpha"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-alpha"
        secretKey: "db-password"
  
  etl-bravo:
    repository: "etl-monorepo-app"
    tag: "01cebb6"
    dbType: "oracle" 
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-bravo"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-bravo"
        secretKey: "db-password"
  
  etl-charlie:
    repository: "etl-monorepo-app"
    tag: "05ab57a"
    dbType: "postgres"
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-shared-postgres"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-shared-postgres"
        secretKey: "db-password"
  
  etl-delta:
    repository: "etl-monorepo-app"
    tag: "05ab57a"
    dbType: "postgres"
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-shared-postgres"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-shared-postgres"
        secretKey: "db-password"
