image:
  pullPolicy: Always

workers:
  etl-alpha:
    repository: "etl-monorepo-app"
    tag: "0fbe0ec"
    dbType: "mysql"
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-alpha"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-alpha"
        secretKey: "db-password"
  
  etl-bravo:
    repository: "etl-monorepo-app"
<<<<<<< HEAD
    tag: "d0598b1"
    dbType: "oracle"
=======
    tag: "d0598b1"
    dbType: "oracle" 
>>>>>>> df76c40d408381362957d6740d589614575b3206
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-bravo"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-bravo"
        secretKey: "db-password"
  
  etl-charlie:
    repository: "etl-monorepo-app"
    tag: "d0598b1"
    dbType: "postgres"
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-shared-postgres"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-shared-postgres"
        secretKey: "db-password"
  
  etl-delta:
    repository: "etl-monorepo-app"
    tag: "d0598b1"
    dbType: "postgres"
    secretEnv:
      BKTNAME:
        secretName: "etl-secret-shared-postgres"
        secretKey: "bucket"
      DB_PASSWORD:
        secretName: "etl-secret-shared-postgres"
        secretKey: "db-password"
