{{- range $name, $config := .Values.workers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-monorepo-{{ $name }}-config
  labels:
    app: etl
    instance: {{ $name }}
data:
  LOGLEVEL: {{ $config.logLevel | default "INFO" | quote }}
  DB_TYPE: {{ $config.dbType | quote }}
  DBUSER: {{ $config.dbUser | quote }}
  HTTP_PROXY_MOCK: "127.0.0.1"
  HTTPS_PROXY_MOCK: "11.22.33.44"
{{- end }}
